version: '2'
services:

    useragent-influxdb:
        container_name: useragent.influxdb
        image: influxdb:1.2.4
        ports:
            - 8083:8083
            - 8086:8086
        environment:
         - INFLUXDB_DB=useragent_metrics
         - INFLUXDB_ADMIN_ENABLED=true
         - INFLUXDB_ADMIN_USER=useragent_admin
         - INFLUXDB_ADMIN_USER=useragent_admin_password
         - INFLUXDB_USER=useragent_user
         - INFLUXDB_USER_PASSWORD=useragent_password
